### ISSUE TITLE
use yarn?

### ISSUE THREAD

**Issue by cironunes** [r31gN/nott#2]

**Comment by r31gN** [comment]
Would you see this as a compatibility thing for the people in love with Yarn? 
I have personally used Yarn some time ago, but once npm 5 came out (with package-lock.json) I switched back. 
I'm not familiar with the differences now. Is it worth using yarn over npm now? Is there still a perf difference or significant differences in approaching the lock files?

**Comment by cironunes** [comment]
It's more about the performance. Maybe we should maintain both (npm and yarn) lock files?

**Comment by cironunes** [comment]
![screen shot 2018-01-16 at 16 55 28](https://user-images.githubusercontent.com/469908/34998005-352e852c-fade-11e7-9aa2-19a2fe535202.png)

**Comment by r31gN** [comment]
Indeed I installed yarn myself and ran yarn install. very fast. added yarn lock file and changed README to mention yarn
